remote_theme: pages-themes/minimal@v0.2.0

logo: /images/28-LOGO-EGAD-RGB_small.jpg
title: [About ICA Records in Contexts Ontology (RiC-O)]
description: [An information website about Records in Contexts Ontology (RiC-O).]